### ISSUE TITLE
创建镜像时会产生两个镜像是什么原因呢

### ISSUE THREAD

**Issue by zhouyaozhouyao** [ZpGuo/zPhal-dockerfiles#2]
Dockerfile文件
```
FROM nginx

MAINTAINER "zhouyao"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

docker-compose.yml文件
```
version: '3.2'
services:
  nginx:
    build: ./nginx
    volumes:
      - ../website:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'
```

查看镜像列表
```
docker images        
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
file_nginx          latest              126bee0ea0b5        17 seconds ago      126MB
nginx               latest              5a3221f0137b        4 days ago          126MB
```
